### ISSUE TITLE
Not able to build in Android Studio 4.2 canary

### ISSUE THREAD

**Issue by ankitdubey021** [romainguy/sample-materials-shop#1]
It is giving error saying **Task 'wrapper' not found in project ':app'.**

**Comment by AndroidDeveloperLB** [comment]
I get this one:

```
Invalid Gradle JDK configuration found. Open Gradle Settings 
```

![image](https://user-images.githubusercontent.com/5357526/84604388-5dccf380-ae9e-11ea-8741-02011d7887ca.png)


Is it the same?

**Comment by ankitdubey021** [comment]
@AndroidDeveloperLB I think in your case, you should open app directory inside sample-material-shops

**Comment by AndroidDeveloperLB** [comment]
@ankitdubey021 Oh. Usually project include what's needed at the top folder.

Anyway, I get this now:

![image](https://user-images.githubusercontent.com/5357526/84954995-18f3c780-b0ff-11ea-9890-3979ab325f6a.png)

**Comment by alexfrostdev** [comment]
Check out this repo. Open its folder and delete .idea. Than open project at AS 4.2. If AS is not crashed project is opened and you can build it.

**Comment by AndroidDeveloperLB** [comment]
@alexfrostdev I get this error:

![image](https://user-images.githubusercontent.com/5357526/85127445-1943ae00-b238-11ea-9f48-abf9d72c88f7.png)

But after a few updates to the project, it worked fine. Thanks.

**Comment by gputhige** [comment]
Using Android Studio Arctic Fox | 2020 | 3.1 Canary 4.
I get the error  
"The project is using an incompatible version (4.2.0-alpha12) of the Android Gradle plugin."
Upgrade to the latest version
However, clicking on Upgrade, nothing happens

Tried changing the manually in build.gradle.kts, but that throws multiple errors.

**Comment by gputhige** [comment]
![aa](https://user-images.githubusercontent.com/20111754/104291539-a6569900-54e1-11eb-8155-89adeefbc1e7.jpg)
